services:
  apibackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api_backend_prj:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    expose:
      - 8001
    environment:
      - DJANGO_SETTINGS_MODULE=network.settings_api
    command: [ "apibackend", "gunicorn", "network.wsgi:application", "--workers", "4", "--bind", "0.0.0.0:8001", "--access-logfile", "-", "--error-logfile", "-" ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
    depends_on:
      - db
  admin_panel:
    image: api_backend_prj:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=network.settings_main
    expose:
      - 8002
    command: [ "adminpanel", "gunicorn", "network.wsgi:application", "--workers", "1", "--bind", "0.0.0.0:8002", "--access-logfile", "-", "--error-logfile", "-" ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    depends_on:
      - apibackend
      - db
      - redis
  redis:
    image: redis:8.2.1-alpine3.22
    container_name: redis_db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    expose:
      - 6379
  celery:
    image: api_backend_prj:latest
    restart: unless-stopped
    container_name: celery_worker
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=network.settings_main
    command: celery -A network worker --loglevel=info
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    depends_on:
      - redis
      - apibackend
  celery_beat:
    image: api_backend_prj:latest
    restart: unless-stopped
    container_name: celery_beat_scheduler
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=network.settings_main
    command: celery -A network beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    depends_on:
      - redis
      - apibackend
      - db
  db:
    image: postgres:17-bookworm
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./backend/.env # add secrets later
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
  nginx:
    image: nginx:1.29.1-alpine-slim
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80 # use "127.0.0.1:80:80" later
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - apibackend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nextjs_frontend:1.0.0
    container_name: nextjs_frontend_con
    expose:
      - 3000
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    command: node server.js
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    depends_on:
      - apibackend

volumes:
  data:
